import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/app/components/Header";
import Footer from "./components/Footer";
import HeaderHolder from "./components/HeaderHolder";
import MyProvider from "./redux/MyProvider";
import DialogWrapper from "./components/Dialogs/DialogWrapper";
import PreventRightClick from "./components/PreventRightClick";
import MobileNavigation from "./components/MobileNavigation";
import MobileNavigationHolder from "./components/MobileNavigationHolder";
import React from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const futura = localFont({
  src: [
    {
      path: "./fonts/futura-pt/FuturaCyrillicLight.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/futura-pt/FuturaCyrillicBook.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/futura-pt/FuturaCyrillicMedium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/futura-pt/FuturaCyrillicDemi.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/futura-pt/FuturaCyrillicBold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/futura-pt/FuturaCyrillicExtraBold.ttf",
      weight: "800",
      style: "normal",
    },
  ],

  variable: "--font-futura-pt",
});

const inter = Inter({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-inter",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${futura.variable} ${inter.variable} font-futura antialiased w-full`}
      >
        <React.Suspense fallback={<></>}>
          <MyProvider>
            <DialogWrapper />
            <PreventRightClick />
            <HeaderHolder>
              <Header />
            </HeaderHolder>
            {children}
            <Footer />
            <MobileNavigationHolder>
              <MobileNavigation />
            </MobileNavigationHolder>
          </MyProvider>
        </React.Suspense>
      </body>
    </html>
  );
}
